server:
  port: 7004
#nacos配置与服务中心
spring:
  application:
    name: order-service7004
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bs_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #server-addr: 192.168.58.133:1111
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
  #RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: mall
    password: mall
    virtual-host: /mall
    publisher-confirm-type: correlated # 开启发送确认
    publisher-returns: true # 开启发送失败退回
    listener:
      direct:
        acknowledge-mode: manual # 开启ACK手动
        prefetch: 5000 #限制direct交换机
      simple:
        acknowledge-mode: manual
        prefetch: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000

logging:
  file:
    path: E:/springbootlog/orderservice7004
  level:
    com:
      example:
        orderservice:
          dao:
            OrderMapper: debug


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.commons.po